[versions]
errorprone-plugin = "5.1.0"
nullaway-plugin = "3.1.0"
spotless-plugin = "7.0.4"
spotbugs-plugin = "6.5.8"
auto-semver = "2.0.0"

errorprone-core = "2.50.0"
nullaway-core = "0.12.7"
google-java-format = "1.27.0"
checkstyle = "10.26.1"

junit-jupiter = "6.0.3"

[libraries]
errorprone-plugin = { module = "net.ltgt.gradle:gradle-errorprone-plugin", version.ref = "errorprone-plugin" }
nullaway-plugin = { module = "net.ltgt.gradle:gradle-nullaway-plugin", version.ref = "nullaway-plugin" }
spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless-plugin" }
spotbugs-plugin = { module = "com.github.spotbugs.snom:spotbugs-gradle-plugin", version.ref = "spotbugs-plugin" }
auto-semver = { module = "io.github.stellarsunset:auto-semver", version.ref = "auto-semver" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

[plugins]
auto-semver = { id = "io.github.stellarsunset.auto-semver", version.ref = "auto-semver" }
